const AppActionTypes = {
  FETCH_REVIEWS_START: "FETCH_REVIEWS_START",
  FETCH_REVIEWS_SUCCESS: "FETCH_REVIEWS_SUCCESS",
  FETCH_REVIEWS_FAILURE: "FETCH_REVIEWS_FAILURE",
  NO_MORE_DATA_RETRIEVED: "NO_MORE_DATA_RETRIEVED",
  FETCH_FILTERED_REVIEWS_SUCCESS: "FETCH_FILTERED_REVIEWS_SUCCESS",
  CLEAR_RESULTS: "CLEAR_RESULTS",
};

export default AppActionTypes;
